---
name: 'Build Ansible Collection'
description: 'Build an Ansible collection tarball'
inputs:
  working-directory:
    description: 'Directory where collection galaxy.yml is located'
    required: false
    default: '.'
outputs:
  tarball:
    description: 'Path to the built collection tarball'
    value: ${{ steps.build.outputs.tarball }}
  collection-name:
    description: 'Name of the collection (namespace-name-version)'
    value: ${{ steps.build.outputs.collection_name }}

runs:
  using: 'composite'
  steps:
    - name: Build collection
      id: build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Building Ansible collection..."
        ansible-galaxy collection build

        # Find the generated tarball
        TARBALL=$(ls -t *.tar.gz | head -n1)
        COLLECTION_NAME=$(basename "$TARBALL" .tar.gz)

        echo "tarball=${{ inputs.working-directory }}/${TARBALL}" >> $GITHUB_OUTPUT
        echo "collection_name=${COLLECTION_NAME}" >> $GITHUB_OUTPUT

        echo "✅ Built collection: ${TARBALL}"
        ls -lh "${TARBALL}"
