---
name: Test Ansible Collection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        ansible-version: ['ansible-core>=2.13,<2.14', 'ansible-core>=2.14,<2.15', 'ansible-core>=2.15,<2.16']

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ansible ${{ matrix.ansible-version }}
        run: |
          python -m pip install --upgrade pip
          pip install "${{ matrix.ansible-version }}"

      - name: Build the collection
        run: |
          ansible-galaxy collection build

      - name: Install the collection
        run: |
          ansible-galaxy collection install kush_gupt-*.tar.gz

      - name: Verify modules are accessible
        run: |
          ansible-doc kush_gupt.minimal_collection.sysctl
          ansible-doc kush_gupt.minimal_collection.ini_file
